DEBUG_LIST = ["2W19KS75"]
BAY_STATUS_LIST = [ "making the bay great again",
                    "adding to the clutter",
                    "doing stuff and things and such",
                    "avoiding assignments",
                    "making the norse god vidar proud",
                    "why don't I have 40 apple interviews yet?",
                    "Not eating",
                    "Sleeping in the comfy leather chair thing",
                    "juggling ignition spacers",
                    "what if we stored all of our fill hoses in a linked list?",
                    ":rocket::rocket::rocket::rocket::rocket::rocket::rocket::rocket::rocket::rocket:",
                    "knolling",
                    "soldering dangerously"]
BAY_LEAVE_STATUS_LIST = ["went home",
                "not in the bay anymore",
                "doing homework or reddit or something",
                "off having adventures and slaying dragons",
                "in the bay only in spirit",
                "oh right, I still have classes",
                "struggling to explain to normies why I spend so much time at rocketry",
                "stripping for money to buy better wire strippers",
                "praying for successful ignition",
                "moved to iceland. Became a shepherd."]
BAY_LEAVE_EMOJI_LIST = [":feelsbadman:",
                        ":rip:",
                        ":sob:",
                        ":robin:"]
ignore_list = [] # Users in this list (identified by user ID) will not show up in "/bay who"

agenda_react_emojis = [
":_partyparrot",
":_anguished:", ":_blush:", ":_disappointed:", ":_eyes:", ":_fearful:",
":_heart:", ":_heart_eyes:", ":_kissing_heart:", ":_neutral_face:",
":_no_mouth:", ":_open_mouth:", ":_pensive:", ":_scream:", ":_smile:",
":_smirk:", ":_sob:", ":_sweat:", ":_thinking_face:", ":_turtle:",
":_upside_down_face:", ":_white_frowning_face:", ":acetone:",
":actually_ham:", ":adam:", ":addreaction:", ":alex:", ":alsoham:",
":amazin:", ":anarchist:", ":aristotle:", ":axe:", ":banan:", ":bean:",
":beret:", ":blackspace:", ":broom:", ":chill:", ":cinnamon:", ":comrade:",
":cosin:", ":cube:", ":cute:", ":cuter:", ":cutest:", ":dab:", ":damn:",
":david:", ":diode:", ":doge:", ":doris:", ":dragoncurve:", ":drill:",
":dundundun:", ":em1:", ":em2:", ":em3:", ":em4:", ":emily:", ":faceless:",
":failfish:", ":feelsbadman:", ":feelsgoodman:", ":feelsmerryman:",
":fox:", ":fpaacs:", ":gain:", ":god:", ":gold:", ":goodstuff:", ":goose:",
":greatstuff:", ":ham:", ":hilbert:", ":hilbertcurve:", ":hilberto:",
":hilly:", ":hotstrippers:", ":hussein:", ":infinity:",
":internalpainmaskedbysmilingexterior:", ":jacob:", ":julia:",
":kappa:", ":kenneth:", ":koch:", ":lad:", ":lambda:", ":logo:", ":logo2:",
":lolsorryadam:", ":mandelbrot:", ":mandelbrotrainbow:", ":matrix:",
":maxq:", ":maxrobin:", ":maxvithusan:", ":mcteerts:", ":menger:", ":meowth:",
":miranda:", ":mirangry:", ":neutral:", ":newhire:", ":nicestuff:",
":nick:", ":nina:", ":ninalul:", ":ninasback:", ":nofrills:", ":noosejs:",
":nugget:", ":nylon:", ":ohgod:", ":opvote:", ":pain:", ":parrot:",
":partyparrot:", ":paylad:", ":pita:", ":pjsalt:", ":pogchamp:",
":polymethlymethacrylate:", ":poutine:", ":praxair:", ":psi:", ":q:",
":rip:", ":robin:", ":ryan:", ":ryerson:", ":sadparrot:", ":sanic:",
":shufflelogo:", ":shufflelogo2:", ":shuffleparrot:", ":shuffleparrot2:",
":sierpinski:", ":sin:", ":siren:", ":sledge:", ":slowpoke:", ":smooth1:",
":smooth2:", ":ssdc:", ":subtle:", ":syzygy:", ":thonking_foce:", ":tru:",
":trump:", ":truss:", ":upvote:", ":uwin:", ":vdar1:", ":vdar10:", ":vdar11:",
":vdar12:", ":vdar13:", ":vdar2:", ":vdar3:", ":vdar4:", ":vdar5:", ":vdar6:",
":vdar7:", ":vdar8:", ":vdar9:", ":vithusan:", ":whitespace:", ":wonk:",
":wow:", ":wreckingball:", ":wtfdiagram:", ":wutface:", ":yash:",
":yiqing:", ":zak:" ]

channels_map = {
"admin": "C709ZGTE0",
"airframe": "C90E34QDD",
"bay_area": "C5H7L6MV5",
"business": "C07MXA613",
"climbing": "C8NMF5USD",
"commies": "C8V6QBY2X",
"coops": "C0JM1E0V7",
"daq": "C2J62F13R",
"documentary": "C8SL6G3J8",
"electrical": "C07MX0QDS",
"flight_instr": "C791WF415",
"flighttest": "C5B3XTG5V",
"floof": "C7AVD76GH",
"fuel": "C5CN621A6",
"fydp": "C6SGS9UB1",
"general": "C07MWEYPR",
"mechanical": "C07MX5JDB",
"offtopic": "C07MWHQRY",
"operations": "C90RA7WG6",
"outings": "C5D4H20SF",
"payload": "C4H4NJG77",
"pcf": "C883LH3RT",
"pholosophy": "C8Z032PJN",
"plants": "C75L2R10D",
"politics": "C88FMJ6GL",
"projects": "C74D886AZ",
"recipes": "C6W3EFW0K",
"recovery": "C8VL7QCG0",
"recruitment": "C0B0JVD4N",
"research": "C3NM5L3GD",
"resumes": "C8SART092",
"rlcs": "C5K2KLWP5",
"safety": "C0K5GS8US",
"sports": "C8TJWSBQE",
"temp": "C73F2AK6E",
"tests": "C5JFT0LTB",
"tower": "C5FCA00KF",
"trellotest": "C7B55M2RX",
"trucktraining_sac18": "C8UKLV5FA",
"uxo": "C79S4M35E",
"vidariv": "C74JAHBS7",
"website": "C6BLGAR7H"}
